---
title: "Streamline reporting"
subtitle: "Reproducible reports with Quarto"

author: 
  name: "John Little"
  orcid: 0000-0002-3600-0972
  affiliation:
    - name: Duke University Libraries
      department: Center for Data & Visualization Sciences
      city: Durham
      state: NC
      country: US
      url:  https://library.duke.edu/data
institute: "Center for Data & Visualization Sciences"
date: today

format: 
  revealjs:
    theme: moon
    self-contained: true  
    footer:  "[John R Little](https://JohnLittle.info) ● [Center for Data & Visualization Sciences](https://library.duke.edu/data/) ● [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)"
    logo: images/rfun_logo.png
    
output-dir: "/docs"    

license: "CC BY"

editor: source
---

## What is reproducibility?

\

Recreate the exact results of a computational analysis or experiment using the same data, code, and methods as the original study.

\

Someone else should be able to follow the same steps and obtain the same outcomes.

\

<center>[CDVS Youtube](https://www.youtube.com/playlist?list=PLXsA_OlR0o0PcuagC_TUl32RULZkLHI1D)</center>

## What is workflow

A structured sequence of data processing, analysis, and computational steps used to transform raw data into meaningful results or insights.\

Typically involves:

-   Data acquisition and preparation
-   Processing and analysis steps
-   Generation of outputs (e.g., results, visualizations)
-   Documentation of the process

<center>Automated and Reproducible</center>

## Quarto

Quarto is a scientific publishing system that enables reproducible workflows and simplifies report generation.

\

Quarto uses notebooks as the primary document format.

\

RStudio and Quarto were introduced and discussed in previous sessions.

\

[[Get Started text with videos](https://intro2r.library.duke.edu/) ● [Exercises, code, slides](https://github.com/libjohn/rforlunch_exercises)]{style="font-size: x-large; display: flex; align-items: center; justify-content: center;"}

## Notebooks

\

A notebook is a document containing code and natural language

-   Jupyter (.ipynb)
-   Quarto document (.qmd) (next-gen R Markdown)

## What we'll learn

Streamlining reproducible workflows - from code to reports (slides, PDF, dahsboards, etc.) that enable reproducible workflows and simplify generating reports from code.

\
Take control of your reports and can reduce dependencies on subscription hosts.

## RStudio configurations

-   Demo a Quarto Manuscript
    -   [Blank Slate Approach to **reproducibility**: RStudio **settings**](https://docs.posit.co/ide/user/ide/get-started/#blank-slate)
    -   **BUILD** `quarto render` [([Render styles](https://quarto.org/docs/guide/))]{style="color: grey; font-size: x-large;"}
    -   `_quarto.yaml` [([Example at Quarto documentation](https://quarto.org/docs/authoring/front-matter.html))]{style="font-size: x-large;"}

## Prerequisites

-   Already installed _tinytex_ on Windows via Terminal [(takes several minutes)]{style="color: grey; font-size: x-large;"}
    -   Rstudio \> Terminal \> `quarto install tinytex`
-   Use **RStudio Project** protocol 
    -   Use git version control [(next week)]{style="color: grey; font-size: x-large;"}
    -   Use {renv} to back-up specific package versions
    -   Use GitHub to manage versions
    -   Link GitHub to Zenodo to mint DOIs and archive milestones [([Instructions](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content))]{style="font-size: x-large;"}

## Prequeisites . . .

\
Bibliography

\
Quarto leverages bib files from from bibliographic reference managers [(Zotero, EndNote)]{style="color: grey;"} and imports relevant citation data from DOIs

-   references.bib - **bibliography file**

## SHOW

Clone [example](https://github.com/quarto-ext/manuscript-template-rstudio) from GitHub

-   RStudio \> Project \> new Project \> Quarto Manuscript  \ ([documentation example](https://github.com/quarto-ext/manuscript-template-rstudio))

## More information:

-   [Çetinkaya-Rundel & Wickham](https://mine-cetinkaya-rundel.github.io/quarto-jsm24/4-manuscripts/4-manuscripts.html)
-   [Quarto documentation on Manuscripts](https://quarto.org/docs/manuscripts/)

## Hands-on

#### Create a Quarto webSite

> `RStudio: File > New Project > New Directory > Quarto Website`

#### Create a Quarto Manuscript

    RStudio: File > New Project > New Directory > Quarto Manuscript

[Or, follow these [directions](https://mine-cetinkaya-rundel.github.io/quarto-jsm24/4-manuscripts/4-manuscripts.html#/getting-started) from Çetinkaya-Rundel & Wickham]{style="font-size: xx-large;"}

## Dashboards

Dashboards: Just like a standard quarto document ([docs](%5BQuarto%20Dashboards%20–%20Quarto%5D(https://quarto.org/docs/dashboards/))). YAML -\> `format: dashboard`

-   Interactivity
    -   Simple interactivity with [HTML Widgets](%5Bhtmlwidgets%20for%20R%5D(https://www.htmlwidgets.org/))
    -   Advanced interactivity with Shiny (server-side) and Observable (client-side)

## More tips

-   Themes
    -   [HTML](%5BHTML%20Theming%20–%20Quarto%5D(https://quarto.org/docs/output-formats/html-themes.html)) \| [slides](%5BReveal%20Themes%20–%20Quarto%5D(https://quarto.org/docs/presentations/revealjs/themes.html))
-   [Includes](%5BIncludes%20–%20Quarto%5D(https://quarto.org/docs/authoring/includes.html)) - child documents reference from parent notebooks
-   [Extensions](%5BQuarto%20Extensions%20–%20Quarto%5D(https://quarto.org/docs/extensions/))
-   [CSS Styles](%5BContent%20Editing%20–%20Quarto%5D(https://quarto.org/docs/visual-editor/content.html#css-styles))
-   [Citations & Bibliographies](%5BCitations%20–%20Quarto%5D(https://quarto.org/docs/authoring/citations.html))
-   [PDF Engines](%5BPDF%20Engines%20–%20Quarto%5D(https://quarto.org/docs/output-formats/pdf-engine.html#installing-tex))
